### ISSUE TITLE
typeorm.io is down

### ISSUE THREAD

**Issue by SunnyTam** [typeorm/typeorm.github.io#47]

**Comment by LPeelen** [comment]
Looks like there is an issue with your Vue.js. The whole site doesn't render at all.

**Comment by michaelbromley** [comment]
The cause is this line: https://github.com/typeorm/typeorm.github.io/blob/ed6b645ae006ecf865b8bbeb4400c4abc77a4828/index.html#L40

It seems that linking to unpkg without specifying a version make it redirect to the newest version with the `latest` tag. vue-i18n seems to have just tagged v9.1.2 as latest: 
![image](https://user-images.githubusercontent.com/6275952/113985025-01332e80-984c-11eb-8a4c-4f7423512a7e.png)

This major version seems to have changed the file structure resulting in a 404
```
(index):40 GET https://unpkg.com/vue-i18n@9.1.2/dist/vue-i18n.js net::ERR_ABORTED 404
index.js:8 Uncaught ReferenceError: VueI18n is not defined
    at index.js:8
(anonymous) @ index.js:8
```

**Comment by SunnyTam** [comment]
I think this issue no longer exists
